name: И Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Revisi贸n del C贸digo
        uses: actions/checkout@v4

      - name: Configuraci贸n de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Instalaci贸n de Dependencias
        run: npm ci

      - name: Linting de C贸digo
        run: npm run lint

      - name: Ejecuci贸n de Pruebas
        run: npm run test:coverage

      - name: Subida del Reporte de Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/